name: Build and Release Extensions

on:
  push:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Select latest Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Cache SwiftGodot Build Artifacts
        uses: actions/cache@v4
        id: swiftgodot-build-cache
        with:
          path: SwiftGodot/.build
          key: swiftgodot-build-${{ runner.os }}-${{ hashFiles('SwiftGodot/.git', 'SwiftGodot/Package.resolved') }}
          restore-keys: |
            swiftgodot-build-${{ runner.os }}-

      - name: Report Cache Status
        run: |
          if [ "${{ steps.swiftgodot-build-cache.outputs.cache-hit }}" = "true" ]; then
            echo "✅ SwiftGodot build cache restored successfully."
          else
            echo "ℹ️ SwiftGodot build cache not found. A full build will be performed and cached for next time."
          fi

      - name: Run build script
        run: |
          chmod +x build.sh
          # The build script will now leverage the cached .build directory,
          # significantly speeding up the SwiftGodot compilation.
          ./build.sh

      - name: Prepare Release Package
        run: |
          mkdir -p staging/addons/ios
          mkdir -p staging/addons/macos

          echo "Copying built libraries..."
          cp -R Bin/ios/* staging/addons/ios/
          cp -R Bin/macos/* staging/addons/macos/

          echo "Creating .gdextension files..."
          
          # --- GameCenter.gdextension ---
          cat > staging/GameCenter.gdextension <<EOF
          [configuration]
          entry_symbol = "swift_entry_point"
          compatibility_minimum = "4.2"

          [libraries]
          macos.release = "res://addons/macos/libGameCenter.dylib"
          ios.release = "res://addons/ios/GameCenter.framework"
          
          [dependencies]
          macos.release = {"res://addons/macos/SwiftGodot.framework" : ""}
          ios.release = {"res://addons/ios/SwiftGodot.framework" : ""}
          EOF

          # --- Bonjour.gdextension ---
          cat > staging/Bonjour.gdextension <<EOF
          [configuration]
          entry_symbol = "swift_entry_point"
          compatibility_minimum = "4.2"
          
          [libraries]
          macos.release = "res://addons/macos/libBonjour.dylib"
          ios.release = "res://addons/ios/Bonjour.framework"

          [dependencies]
          macos.release = {"res://addons/macos/SwiftGodot.framework" : ""}
          ios.release = {"res://addons/ios/SwiftGodot.framework" : ""}
          EOF
          
          # --- Haptics.gdextension ---
          cat > staging/Haptics.gdextension <<EOF
          [configuration]
          entry_symbol = "swift_entry_point"
          compatibility_minimum = "4.2"
          
          [libraries]
          macos.release = "res://addons/macos/libHaptics.dylib"
          ios.release = "res://addons/ios/Haptics.framework"

          [dependencies]
          macos.release = {"res://addons/macos/SwiftGodot.framework" : ""}
          ios.release = {"res://addons/ios/SwiftGodot.framework" : ""}
          EOF
          
          # --- InAppPurchase.gdextension ---
          cat > staging/InAppPurchase.gdextension <<EOF
          [configuration]
          entry_symbol = "swift_entry_point"
          compatibility_minimum = "4.2"

          [libraries]
          macos.release = "res://addons/macos/libInAppPurchase.dylib"
          ios.release = "res://addons/ios/InAppPurchase.framework"

          [dependencies]
          macos.release = {"res://addons/macos/SwiftGodot.framework" : ""}
          ios.release = {"res://addons/ios/SwiftGodot.framework" : ""}
          EOF

          # --- Settings.gdextension ---
          cat > staging/Settings.gdextension <<EOF
          [configuration]
          entry_symbol = "swift_entry_point"
          compatibility_minimum = "4.2"

          [libraries]
          macos.release = "res://addons/macos/libSettings.dylib"
          ios.release = "res://addons/ios/Settings.framework"

          [dependencies]
          macos.release = {"res://addons/macos/SwiftGodot.framework" : ""}
          ios.release = {"res://addons/ios/SwiftGodot.framework" : ""}
          EOF
          
          echo "Creating ZIP archive..."
          (cd staging && zip -r ../godot-ios-extensions.zip .)

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: godot-ios-extensions.zip
